export * from "./src/common/globs.js";
export { default as commonConfig } from "./src/configs/acommon.js";
export { default as baseLooseConfig } from "./src/configs/base.loose.js";
export { default as baseStrictConfig } from "./src/configs/base.strict.js";
export { default as jsdocLooseConfig } from "./src/configs/jsdoc.loose.js";
export { default as jsdocStrictConfig } from "./src/configs/jsdoc.strict.js";
export { default as styleLooseConfig } from "./src/configs/style.loose.js";
export { default as styleStrictConfig } from "./src/configs/style.strict.js";
export { default as testLooseConfig } from "./src/configs/test.loose.js";
export { default as testStrictConfig } from "./src/configs/test.strict.js";
export * from "./src/configs/typescript/parser.js";
export * from "./src/presets/base.js";
